### ISSUE TITLE
Add section highlighting community contributions

### ISSUE THREAD

**Issue by tthibo** [ap-datakit/ap-datakit.github.io#13]
We should make sure to include and highlight community-developed extensions.
Here are two to start with:
https://bitbucket.org/quickhand/datakit-data-gdrive/src/master/
https://bitbucket.org/quickhand/datakit-bitbucket/src/master/

Not sure yet if there is an extension for [datasette](https://simonwillison.net/2017/Nov/13/datasette/) yet, but I know there was some talk about that, as well.

**Comment by larryfenn** [comment]
Pushed up the changes to the main site highlighting the two projects linked.
